include theos/makefiles/common.mk

BUNDLE_NAME = MySpacePlugin MySpacePluginPrefs
MySpacePlugin_FILES = MySpacePlugin.m API/MSApi.m API/MSOnsiteContext.m API/MSOffsiteContext.m API/MSRoaApi.m API/MSRestV1.m API/MSOpenSearchApi.m API/MSSecurityContext.m API/OAConsumer.m API/OAMutableURLRequest.m API/OADataFetcher.m API/OAToken.m API/SBJSON.m API/OAHMAC_SHA1SignatureProvider.m API/OARequestParameter.m API/OAServiceTicket.m API/SBJsonBase.m API/SBJsonWriter.m API/SBJsonParser.m API/MSConstants.m API/Base64.m API/NSString+URLEncoding.m API/NSMutableURLRequest+Parameters.m API/NSURL+Base.m
MySpacePlugin_FRAMEWORKS = UIKit CoreGraphics CoreLocation
MySpacePlugin_INSTALL_PATH = /Library/Application Support/Fusion/Plugins

MySpacePluginPrefs_FILES = MySpacePluginPrefs.m HSMySpaceActivation.m API/MSApi.m API/MSOnsiteContext.m API/MSOffsiteContext.m API/MSRoaApi.m API/MSRestV1.m API/MSOpenSearchApi.m API/MSSecurityContext.m API/OAConsumer.m API/OAMutableURLRequest.m API/OADataFetcher.m API/OAToken.m API/SBJSON.m API/OAHMAC_SHA1SignatureProvider.m API/OARequestParameter.m API/OAServiceTicket.m API/SBJsonBase.m API/SBJsonWriter.m API/SBJsonParser.m API/MSConstants.m API/Base64.m API/NSString+URLEncoding.m API/NSMutableURLRequest+Parameters.m API/NSURL+Base.m
MySpacePluginPrefs_INSTALL_PATH = /Library/Application Support/Fusion/Plugins/MySpacePlugin.bundle
MySpacePluginPrefs_FRAMEWORKS = UIKit
MySpacePluginPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
