include theos/makefiles/common.mk

BUNDLE_NAME = Google GooglePrefs
Google_FILES = Google.m GoogleView.m
Google_FRAMEWORKS = UIKit CoreLocation
Google_INSTALL_PATH = /Library/Application Support/Fusion/Plugins

GooglePrefs_FILES = GooglePrefs.m
GooglePrefs_INSTALL_PATH = /Library/Application Support/Fusion/Plugins/Google.bundle
GooglePrefs_FRAMEWORKS = UIKit 
GooglePrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
